import java.awt.*;
import java.awt.event.*;
import javax.swing.event.*;
import javax.swing.*;

public class GameOfLife extends JPanel {
	public static Mosaic mosaic;			// Mosaic - the game box
	public static int delay;				// Delay for game step in ms
	public static Timer timer;				// Time for game step
	public static JSlider timeSlider;		// Slider to adjust delay
	public static JButton timerBtn;			// Button to start/stop game
	public static int windowX;
	public static int windowY;
	
	public static void main(String[] args)
	{
		// Create content panels
		GameOfLife content = new GameOfLife();

		// Setup the window and add content to it
		JFrame window = new JFrame("Conways Game of Life");
		window.setContentPane(content);
		window.setSize(windowX, windowY);
		window.setLocation(100, 100);
		window.setVisible(true);
		window.setResizable(false);
		window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);	
	}
	
	/**
	 * Game Constructor
	 */
	public GameOfLife() {
		// Set All Game Defaults
		delay = 100;						// Default time step (ms)
		int numXCells = 80;					// Number of cells in X
		int numYCells = 80;					// Number of cells in Y
		int cellSize = 7;					// cell size in px
		int cellGap = 0;					// gap between cells (not good with light background)
		int lowerTimeStep = 20;				// Fastest time step
		int upperTimeStep = 500;			// Slowest time step
		windowX = numXCells * (cellSize + cellGap) + 110;		// Set Window size to fit everything
		windowY = numYCells * (cellSize + cellGap) + 110;		// Set Window size to fit everything
		
		// Create Objects
		JPanel centerPanel = new JPanel();
		JPanel eastPanel= new JPanel();
		mosaic = new Mosaic (numXCells, numYCells, cellSize, cellGap);
		JButton btn = new JButton("Reset");
		JButton step = new JButton("Step");
		timerBtn = new JButton("Start");
		timeSlider = new JSlider(lowerTimeStep, upperTimeStep, delay);
		
		// Set Layout, labels, and sizes
		setLayout(new BorderLayout());
		timeSlider.setLabelTable( timeSlider.createStandardLabels(75) );
		timeSlider.setPaintLabels(true);
		eastPanel.setLayout(new GridLayout(3,1));
		eastPanel.setPreferredSize(new Dimension(100, 25));
		
		// Setup Listeners
		ButtonHandler listener = new ButtonHandler();
		TimerHandler timerListener = new TimerHandler();
		btn.addActionListener(listener);
		timerBtn.addActionListener(listener);
		step.addActionListener(listener);
		ChangeHandler changeListener = new ChangeHandler(); 
		timeSlider.addChangeListener(changeListener);
		timer = new Timer(delay, timerListener);
		
		// Add Content
		centerPanel.add(mosaic);
		eastPanel.add(btn);
		eastPanel.add(timerBtn);
		eastPanel.add(step);
		add(centerPanel, BorderLayout.CENTER);
		add(eastPanel, BorderLayout.EAST);
		add(timeSlider, BorderLayout.SOUTH);
	}
	
	/**
	 * Paint the graphics for the window, buttons, etc.
	 */
	public void paintComponent(Graphics g) {
		super.paintComponent(g);
	}
	
	/**
	 * Handles all button press events
	 */
	private static class ButtonHandler implements ActionListener {
		public void actionPerformed(ActionEvent e) {
			String command = e.getActionCommand();
			
			// Regenerate a new random grid
			if (command.equals("Reset")) {
				mosaic.regenGrid();
			}
			
			// Proceed the game forward one step
			else if (command.equals("Step")) {
				mosaic.stepGame();
			}
			
			// Start or stop the timer
			else {
				if (!timer.isRunning()) {
					timer.start();
					timerBtn.setText("Pause");
				}
				
				else {
					timer.stop();
					timerBtn.setText("Start");
				}
			}
			
			// Repaint the game grid
			mosaic.repaint();
		}
	}
	
	/**
	 * Handles the timer event - steps the game foward each time the timer goes off
	 *
	 */
	private static class TimerHandler implements ActionListener {
		public void actionPerformed(ActionEvent e) {
			mosaic.stepGame();
			mosaic.repaint();
		}
	}
	
	/**
	 * Handles the events generated by the JSlider
	 * Adjusts the game step timer delay on the fly
	 */
	private static class ChangeHandler implements ChangeListener {
		public void stateChanged(ChangeEvent evnt) {
			timer.setDelay(timeSlider.getValue());
		}
	}
}
